DROP TABLE TDIRORQ;
DROP TABLE CONOBR;
DROP TABLE CONSOLI;
DROP TABLE OBRASOLI;
DROP TABLE TDIRECT;
DROP TABLE TCONCIER;
DROP TABLE TORQUES;
DROP TABLE TOBRA;
DROP TABLE TCOMPOS;
DROP TABLE TSOLIS;



CREATE TABLE TDIRECT (
  NUMDIR NUMBER(3) PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  DIRECCION VARCHAR2(100),
  FECNA DATE,
  TITULAR VARCHAR2(2)
);
CREATE TABLE TORQUES(
    NUMORQ NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(80),
    DIRECCION VARCHAR2(100),
    TEMPORADA VARCHAR2(80),
    FECIN DATE
);
/* TABLA RELACIONAL TDIRECT-TORQUES */
CREATE TABLE TDIRORQ(
  NUMDIR NUMBER(3),
  NUMORQ NUMBER(3),
  PRIMARY KEY(NUMDIR,NUMORQ),
  CONSTRAINT FK_NUMDIR
    FOREIGN KEY(NUMDIR)
      REFERENCES TDIRECT(NUMDIR) ON DELETE CASCADE,
  CONSTRAINT FK_NUMORQ
    FOREIGN KEY(NUMORQ)
      REFERENCES TORQUES(NUMORQ) ON DELETE CASCADE
);

CREATE TABLE TCONCIER(
  NUMCON NUMBER(3) PRIMARY KEY,
  NUMORQ NUMBER(3),
  NOMBRE VARCHAR2(80),
  CONSTRAINT FK_NUMORQUES
    FOREIGN KEY (NUMORQ)
      REFERENCES TORQUES(NUMORQ) ON DELETE CASCADE
);
CREATE TABLE TCOMPOS(
  NUMCOMP NUMBER(3) PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  FECNA DATE,
  DECDEP DATE
);
CREATE TABLE TOBRA(
  NUMOBR NUMBER(3) PRIMARY KEY,
  TITULO VARCHAR2(80),
  NUMCOMP NUMBER(3),
  CONSTRAINT FK_NUMCOMP
    FOREIGN KEY(NUMCOMP)
      REFERENCES TCOMPOS(NUMCOMP) ON DELETE CASCADE
);
CREATE TABLE TSOLIS(
  NUMSOLIS NUMBER(3) PRIMARY KEY,
  NOMBRE VARCHAR(80),
  FECNA DATE,
  INSTRUMENTO VARCHAR2(80)
);
CREATE TABLE CONOBR(
  NUMCON NUMBER(3),
  NUMSOLI NUMBER(3),
  PRIMARY KEY(NUMCON,NUMSOLI),
  CONSTRAINT FK_NUMCON
    FOREIGN KEY(NUMCON)
      REFERENCES TCONCIER(NUMCON) ON DELETE CASCADE,
  CONSTRAINT NUMSOLI
    FOREIGN KEY(NUMSOLI)
      REFERENCES TSOLIS(NUMSOLIS) ON DELETE CASCADE
);
CREATE TABLE CONSOLI(
  NUMCON NUMBER(3),
  NUMSOLI NUMBER(3),
  PRIMARY KEY(NUMCON,NUMSOLI),
  CONSTRAINT FK_NUMCONC
    FOREIGN KEY(NUMCON)
      REFERENCES TCONCIER(NUMCON) ON DELETE CASCADE  ,
  CONSTRAINT FK_NUMSOLI
    FOREIGN KEY(NUMSOLI)
      REFERENCES TSOLIS(NUMSOLIS) ON DELETE CASCADE
);
CREATE TABLE OBRASOLI(
  NUMOBR NUMBER(3),
  NUMSOLIS NUMBER(3),
  PRIMARY KEY(NUMOBR,NUMSOLIS),
  CONSTRAINT FK_NUMOBR
    FOREIGN KEY(NUMOBR)
      REFERENCES TOBRA(NUMOBR) ON DELETE CASCADE,
  CONSTRAINT FK_NUMSOLIS
    FOREIGN KEY(NUMSOLIS)
      REFERENCES TSOLIS(NUMSOLIS) ON DELETE CASCADE
);
