CREATE -- Create a new relational table with 3 columns

CREATE TABLE TDIRECT (
  NUMDIR NUMBER(3) NOT NULL C,
  NOMBRE VARCHAR2(80),
  DIRECCION VARCHAR2(100)
  FECNA DATE()
  TITULAR BOOLEAN()
);
CREATE TABLE TORQUES(
    NUMORQ NUMBER(3) NOT NULL,
    NOMBRE VARCHAR2(80),
    DIRECCION VARCHAR2(100),
    TEMPORADA VARCHAR2(80),
    FECIN DATE(),
    NUMDIR
)
ALTER TABLE TDIRECT(
    CONNSTRAINT PK_TDIRECT_NUMDMIR PRIMARY KEY (NUMDIR)
        REFERENCE 
)