/* Procedimientos */
/* Procedimiento que agrega un director */
CREATE OR REPLACE PROCEDURE DIRECTADD
    (V_NUMDIR IN TDIRECT.NUMDIR%TYPE,
    V_NOMBRE IN TDIRECT.NOMBRE%TYPE, V_DIRECCION IN TDIRECT.DIRECCION%TYPE,
    V_FECNA IN TDIRECT.FECNA%TYPE, V_TITULAR IN TDIRECT.TITULAR%TYPE)
    IS
    BEGIN
        INSERT INTO TDIRECT VALUES(V_NUMDIR,V_NOMBRE,V_DIRECCION,V_FECNA,V_TITULAR);
    END DIRECTADD;

    DECLARE
    V_NUMDIR TDIRECT.NUMDIR%TYPE:=&V_NUMDIR;
    V_NOMBRE TDIRECT.NOMBRE%TYPE :=&V_NOMBRE;
    V_DIRECCION TDIRECT.DIRECCION%TYPE :=&V_DIRECCION;
    V_FECNA TDIRECT.FECNA%TYPE :=&V_FECNA;
    V_TITULAR TDIRECT.TITULAR%TYPE :=&V_TITULAR;
    V_COD TDIRECT.NUMDIR%TYPE;
    BEGIN
        SELECT MAX(TDIRECT.NUMDIR)+1 INTO V_COD FROM TDIRECT;
        DIRECTADD(V_COD,V_NOMBRE,V_DIRECCION,V_FECNA,V_TITULAR);
    END;
    select * from TDIRECT;
    ROLLBACK;

    /* PROCEDIMIENTO PARA SABER SI UN DIRECTOR ES INVITADO O TITULAR */
    DROP PROCEDURE OBRACOMPO;
    CREATE OR REPLACE PROCEDURE OBRACOMPO
    AS
        CURSOR C1 IS
        SELECT *
        FROM TDIRECT X;
        REGISTRO C1%ROWTYPE;
    BEGIN
        OPEN C1;
        FETCH C1 INTO REGISTRO;
        WHILE(C1%FOUND) LOOP
        /* IF REGISTRO.NUMDIR=1  THEN */
            /* DBMS_OUTPUT.PUT_LINE('SI'); */
        /* END IF; */
            IF REGISTRO.TITULAR LIKE ('NO') THEN
                DBMS_OUTPUT.PUT_LINE('EL DIRECTOR ' || REGISTRO.NOMBRE || ' ES UN INVITADO');
            ELSE
                DBMS_OUTPUT.PUT_LINE('EL DIRECTOR ' || REGISTRO.NOMBRE || ' ES TITULAR');
            END IF;
            FETCH C1 INTO REGISTRO;
        END LOOP;
        CLOSE C1;
    END;
    DECLARE 
    BEGIN
        OBRACOMPO();
    END;

    /* MOSTRAR TODAS LAS ORQUESTAS DE UNA TEMPORADA DADA */
    DROP PROCEDURE ESTACION
    CREATE OR REPLACE PROCEDURE ESTACION
    (V_ESTACION IN TORQUES.TEMPORADA%TYPE)
    AS
        CURSOR C1 IS
        SELECT *
        FROM TORQUES X
        WHERE X.TEMPORADA = V_ESTACION;
        REGISTRO C1%ROWTYPE;
    BEGIN
    OPEN C1;
    FETCH C1 INTO REGISTRO;
    WHILE(C1%FOUND) LOOP
        DBMS_OUTPUT.PUT_LINE(REGISTRO.NOMBRE||' '||REGISTRO.DIRECCION|| ' '||REGISTRO.TEMPORADA|| ' ' ||REGISTRO.FECIN);
        FETCH C1 INTO REGISTRO;
    END LOOP;
    CLOSE C1;
    END;
    SHOW ERRORS;
    DECLARE
    V_ESTACION TORQUES.TEMPORADA%TYPE := &V_ESTACION;
    BEGIN
        ESTACION(V_ESTACION);
    END;


    
