/* Procedimientos */
CREATE OR REPLACE PROCEDURE DIRECTADD
    (V_NUMDIR IN TDIRECT.NUMDIR%TYPE,
    V_NOMBRE IN TDIRECT.NOMBRE%TYPE, V_DIRECCION IN TDIRECT.DIRECCION%TYPE,
    V_FECNA IN TDIRECT.FECNA%TYPE, V_TITULAR IN TDIRECT.TITULAR%TYPE)
    IS
    BEGIN
        INSERT INTO TDIRECT VALUES(V_NUMDIR,V_NOMBRE,V_DIRECCION,V_FECNA,V_TITULAR);
    END DIRECTADD;

    DECLARE
    V_NUMDIR TDIRECT.NUMDIR%TYPE:=&V_NUMDIR;
    V_NOMBRE TDIRECT.NOMBRE%TYPE :=&V_NOMBRE;
    V_DIRECCION TDIRECT.DIRECCION%TYPE :=&V_DIRECCION;
    V_FECNA TDIRECT.FECNA%TYPE :=&V_FECNA;
    V_TITULAR TDIRECT.TITULAR%TYPE :=&V_TITULAR;
    V_COD TDIRECT.NUMDIR%TYPE;
    BEGIN
        SELECT MAX(TDIRECT.NUMDIR)+1 INTO V_COD FROM TDIRECT;
        DIRECTADD(V_COD,V_NOMBRE,V_DIRECCION,V_FECNA,V_TITULAR);
    END;
    select * from TDIRECT;
    ROLLBACK;