/* SELECT TDIRECT.NOMBRE, TORQUES.NOMBRE,TORQUES.TEMPORADA,TCONCIER.NOMBRE,
TCOMPOS.NOMBRE,TOBRA.TITULO,TSOLIS.NOMBRE
FROM TDIRECT,TORQUES,TCONCIER,TCOMPOS,TOBRA,TSOLIS
WHERE TDIRECT.NUMDIR = TORQUES.NUMDIR AND TORQUES.NUMORQ = TCONCIER.NUMORQ
AND TCONCIER.NUMCON = CONOBR.NUMCON AND CONOBR.NUMOBR = TOBRA.NUMOBR AND
TOBRA.NUMCOMP = TCOMPOS.NUMCOMP AND TCONCIER.NUMCON = CONSOLI.NUMCON AND
CONSOLI.NUMSOLI = TSOLIS.NUMSOLIS */
SELECT * FROM TDIRECT

SELECT TDIRECT.NOMBRE , TORQUES.NOMBRE,TCONCIER.NOMBRE
FROM TDIRECT,TORQUES,TCONCIER
WHERE TDIRECT.NUMDIR = TORQUES.NUMDIR AND TORQUES.NUMORQ = TCONCIER.NUMORQ
Ç